api:
  url: "http://numbersapi.com/random/trivia?json"

topic:
  name: "records_from_api"


logging:
  level:
    org.springframework.web: ERROR
    com.example: INFO
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    console: "%d %-5level %logger : %msg%n"
  file:
    name: C:/WorkWithAPI/logs